#--------------Welcome to the Death Messages Plus config file.--------------#

# This is a very easy to configure file. There are a things keys you need to know thought.

# %player% Is the player who died. IE: itunes89 died
# %world% The world the user died in. IE: itunes89 died in the world: world_the_end
# %displayname% This is the users display name. IE: Owner itunes89 died.
# %killer% Is the killer. This can be a mob or a player depending on the message. IE: itunes89 was slain by skipperguy12 or itunes89 was slain by a zombie
# %weapon% This is the object used to kill the player. This will only be used in the PvP section.(Lines 44)

# Example: "&b%player% was murdered by %killer% with a powerful %weapon% in %world%." --> V
# (All in aqua) itunes89 was murdered by skipperguy12 with a powerful Diamond Sword in World.

# Easy right! Now for color codes the fun part!

#--------------All color/style codes--------------#
# To see what the colors look like check this out: http:www.minecraftwiki.netwikiFormatting_codes#Color_codes

# &b = Aqua 
# &0 = Black
# &l = Bold
# &3 = Dark Aqua
# &1 = Dark Blue
# &8 = Dark Gray 
# &2  = Dark Green
# &4 = Dark Red
# &6 = Gold
# &7 = Gray
# &a = Green
# &o = Italic
# &k = Random character(s)
# &c = Red
# &r = Reset 	WARNING: If you have &r%player% &resetdied by %killer% Everything after the reset will be back the basic color.
# &m = Strike
# &n = Underline
# &f = White
# &e = Yellow

# Log player deaths in a file
dmp.deaths-logging: true
# Used for DMP's development
dmp.debug: true
dmp.yaml-version: 0

arrows.default: "%player% was shot by %killer%"
arrows.using: "%player% was shot by %killer% using %item"
snowballs.pummeled: "%player% was pummeled by %killer%"
snowballs.pummeled.using: "%player% was pummeled by %killer% using %item%"
cactus.default: "%player% was pricked to death"
cactus.escape: "%player% walked into a cactus whilst trying to escape %killer%"
cramming.default: "%player% was squished too much"
cramming.escape: "%player% was squashed by %killer%"
drowning.default: "%player% drowned"
downing.escape: "%player% drowned whilst trying to escape %killer%"
elytra.default: "%player% experienced kinetic energy"
elytra.escape: "%player% experienced kinetic energy whilst trying to escape %killer%"
explosion.default: "%player% blew up"
explosion.escape: "%player% was blown up by %killer%"
explosion.using: "%player% was blown up by %killer% using %item%"
explosion.game-design: "%player% was killed by %item%"
falling.default.small:
  - "Dirt got on %player%'s shoes and they died"
  - "%player% hurt his wittle body"
falling.default.large: "%player% fell from a high place"
falling.escape: "%player% hit the ground too hard whilst trying to escape %killer%"
falling.ladder: "%player% fell off a ladder"
falling.vines: "%player% fell off some vines"
falling.vines-weeping: "%player% fell off some weeping vines"
falling.vines-twisted: "%player% fell off some twisting vines"
falling.scaffolding: "%player% fell off scaffolding"
falling.climbing: "%player% fell while climbing"
falling.water-accident: "death.fell.accident.water"
falling.impaled.default: "%player% was impaled on a stalagmite"
falling.impaled.escape: "%player% was impaled on a stalagmite whilst fighting %killer%"
falling-block.anvil.default: "%player% was squashed by a falling anvil"
falling-block.anvil.escape: "%player% was squashed by a falling anvil whilst fighting %killer%"
falling-block.default: "%player% was squashed by a falling block"
falling-block.escape: "%player% was squashed by a falling block whilst fighting %killer%"
falling-block.stalactite.default: "%player% was skewered by a falling stalactite"
falling-block.stalactite.escape: "%player% was skewered by a falling stalactite whilst fighting %killer%"
fire.default: "%player% went up in flames"
fire.default.escape: "%player% walked into fire whilst fighting %killer%"
fire-burned.default: "%player% burned to death"
fire-burned.escape: "%player% was burnt to a crisp whilst fighting %killer%"
fireworks.default: "%player% went off with a bang"
fireworks.default.escape.by: "%player% went off with a bang due to a firework fired from <item> by %killer%"
lava.default: "%player% tried to swim in lava2"
lava.escape: "%player% tried to swim in lava to escape %killer%2"
lightning.default: "%player% was struck by lightning"
lightning.escape: "%player% was struck by lightning whilst fighting %killer%"
magma-block.default: "%player% discovered the floor was lava"
magma-block.escape: "%player% walked into danger zone due to %killer%"
magic.default: "%player% was killed by magic"
magic.default.escape: "%player% was killed by magic whilst trying to escape %killer%"
magic.default.escape.by: "%player% was killed by %killer% using %item%"
powder-snow.default: "%player% froze to death"
powder-snow.escape: "%player% was frozen to death by %killer%"
killed.by: "%player% was slain by %killer%"
killed.by.using: "%player% was slain by %killer% using %item%"
killed.by.fireball: "%player% was fireballed by %killer%"
killed.by.fireball.using: "%player% was fireballed by %killer% using %item%"
killed.stung: "%player% was stung to death"
killed.strung.using: "death.attack.sting.item"
killed.skull: "%player% was shot by a skull from %killer%"
killed.skull.by: "death.attack.witherSkull.item"
starving.default: "%player% starved to death"
starving.escape: "%player% starved to death whilst fighting %killer%"
suffocation.default: "%player% suffocated in a wall"
suffocation.escape: "%player% suffocated in a wall whilst fighting %killer%"
sweet-berry-bush.default: "%player% was poked to death by a sweet berry bush"
sweet-berry-bush.escape: "%player% was poked to death by a sweet berry bush whilst trying to escape %killer%"
thorns.default: "%player% was killed trying to hurt %killer%"
thorns.using: "%player% was killed by <item> trying to hurt %killer%"
trident.default: "%player% was impaled by %killer%"
tident.escape: "%player% was impaled by %killer% with %item%"
void.default: "%player% fell out of the world"
void.escape: "%player% didn't want to live in the same world as %killer%"
wither.default: "%player% withered away"
wither.escape: "%player% withered away whilst fighting %killer%"
drying-out.default: "%player% died from dehydration"
drying-out.escape: "%player% died from dehydration whilst trying to escape %killer%"
generic.default: "%player% died"
generic.default.by: "%player% died because of %killer%"
dragon.roasted: "%player% was roasted in dragon breath"
dragon.roasted.by: "%player% was roasted in dragon breath by %killer%"
